import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home(): JSX.Element {
  const [isSettingUpNickName, setIsSettingUpNickName] = useState(false);

  const router = useRouter();

  const HandlerSubmitNickName = (
    event: React.SyntheticEvent<HTMLFormElement> | any | undefined
  ) => {
    event.preventDefault();

    // Set Loading to be True
    setIsSettingUpNickName(true);

    // Get Nickname value
    const Nickname: string = event.target.nickname.value.trim();

    // Do Nothing is Nickname is empty
    if (!Nickname) {
      return;
    }

    setTimeout(() => {
      // Set Loading to be False
      setIsSettingUpNickName(false);

      // Save to Local Storage
      localStorage.setItem("nickname", Nickname);

      // Set back to empty String
      event.target.nickname.value = "";

      // Push to Start Quiz page
      router.push("/chat");
    }, 3000);
  };

  return (
    <>
      <Head>
        <title>Live Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="quiz-app-section">
          <div className="quiz-app-container">
            <div className="quiz-app-text-container">
              <h2>Choose a Nickname</h2>
              <p>
                Nicknames are used to identify different devices in a common
                file sharing room. A room must always have devices with unique
                nicknames.
              </p>
            </div>
            <div className="quiz-app-form-container">
              <form
                className="quiz-app-form"
                method="POST"
                onSubmit={HandlerSubmitNickName}
              >
                <input
                  type="text"
                  name="nickname"
                  id="nickname"
                  placeholder="Blyncnov is a cool nickname 😊"
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    e.target.value
                  }
                />
                <button>
                  {!isSettingUpNickName ? "Setup Nick-Name" : "Loading..."}
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
